#ifndef KEYPAD_CFG
#define KEYPAD_CFG

#define  KEYPAD_COL1 PINC5
#define  KEYPAD_COL2 PINC6
#define  KEYPAD_COL3 PINC7

#define  KEYPAD_RAW1 PINC2
#define  KEYPAD_RAW2 PINC3
#define  KEYPAD_RAW3 PINC4
#endif